### ISSUE TITLE
When running Odin with Vokrii Novice Spell Tomes display <Level> instead of Novice.

### ISSUE THREAD

**Issue by ItsAlways710** [tr4wzified/DisplaySpellTomeLevelPatcher#10]
If I disable Vokrii it names them properly, I don't think the Vokrii dirty fix is renaming the vanilla Novice spells.

**Comment by lbotticchio** [comment]
I am having the same issue.

**Comment by ItsAlways710** [comment]
It’s Vokrii causing it, I ended up disabling Vokrii (and patches), running synthesis with just the displayspelltomelevelpatcher, then forwarding everything into a final patch, then re-enable Vokrii and patches, then run synthesis without the displlayspelltomelevel patcher – I then have everything synthesis would have done, most in synthesis patch, some in my final patch…

**Comment by lbotticchio** [comment]
@caseygisler - Thanks!  I was going to be lazy and just leave it  but you have inspired me to do it properly!

**Comment by lbotticchio** [comment]
@caseygisler - That worked perfectly! I had to disable Odin as well so maybe something in the Enai-verse is causing the issue.

**Comment by Odie** [comment]
Hi there, I think this might be caused by bug in the code.

In DisplaySpellTomeLevelPatcher/Program.cs#L113-L127

```
                if (bookName.Contains(levelFormatVariable))
                {
                    foreach (string skillLevel in skillLevels)
                    {
                        if (halfCostPerkContext.ModKey == Vokrii && halfCostPerk.Description != null) <1>
                        {
                            if (!DescriptionContain(halfCostPerk, skillLevel)) continue;
                        }
                        else if (!NamedFieldsContain(halfCostPerk, skillLevel)) continue; <2>

                        bookName = bookName.Replace(levelFormatVariable, skillLevel); <3>
                        changed = true;
                        break;
                    }
                }
```

It looks like it might be performing some kind of string replacement at <3>, but it can be bypassed by <1> and <2>, which will leave the "<level>" tags un-replaced.

**Comment by Soukmancer** [comment]
I am not using Vokii or Odin.  I am using Mysticism and Adamant.   But it appears all Novice and Apprentice spells are appearing as <level>

**Comment by tr4wzified** [comment]
Try again after the latest changes.

**Comment by tr4wzified** [comment]
Since level is not determined by using the half cost perk anymore this should have been fixed sometime ago
