### ISSUE TITLE
Incompatible with Better Spell Learning

### ISSUE THREAD

**Issue by H-QueerCoded** [tr4wzified/DisplaySpellTomeLevelPatcher#11]
Better Spell Learning removes books directly teaching you a spell and replaces it with a script, so spell books modified by it and its patches don't get their names changed by this patcher.

From what I can tell from looking in xEdit, I would think it would be possible to check if the book has the `SpellTomeReadScript` attached and then get the data on the spell from the Script's properties.

Here are the relevant property names i found:
`School` a string of the spell's school
`SpellLearned` the FormID of the learned spell

**Comment by tr4wzified** [comment]
Try again after the latest changes.

**Comment by tr4wzified** [comment]
Implemented a while back by Jampion
