### ISSUE TITLE
Suggested Fix for Vokrii & another bug

### ISSUE THREAD

**Issue by audriuska12** [tr4wzified/DisplaySpellTomeLevelPatcher#12]
I've found a way to fix the Vokrii bug:
Line 130:
Current code:
bookName.Replace(levelFormatVariable, "Novice");
Working code:
bookName = bookName.Replace(levelFormatVariable, "Novice");
changed = true;

Additional bug discovered: spell names with colons are cut off. Fix:
Line 63:
Old code: 
return spellTomeName.Split(": ")[1];
Working code:
return string.Join(": ", spellTomeName.Split(": ").Skip(1));

**Comment by Soukmancer** [comment]
I don't use Vokrii, but experience the same issue with Adamant / Mysticism, would this also help?

**Comment by audriuska12** [comment]
Unfortunately, the Vokrii fix is in this if block:
                if (halfCostPerkContext.ModKey == Vokrii && bookName.Contains(levelFormatVariable))
It's _possible_ that it might be as simple as duplicating the Vokrii handling code and replacing everything with Adamant/Mysticism (whichever provides the perk), but I can make no promises at all.

**Comment by audriuska12** [comment]
...Unfortunately, playing with it further shows that while the spell tomes get renamed, the levels aren't always accurate.

**Comment by Soukmancer** [comment]
does this mean you are not the one to fulfill the prophecy?

**Comment by tr4wzified** [comment]
Try again after the latest changes.

**Comment by tr4wzified** [comment]
Since level is not determined by using the half cost perk anymore this should have been fixed sometime ago
