### ISSUE TITLE
Sparks spell

### ISSUE THREAD

**Issue by ronamit** [tr4wzified/DisplaySpellTomeLevelPatcher#4]
Hi, nice work!
I do have a small issue
I am using Odin, and the spell tome for Sparks  is titled Master (but the spell is novice)
Here is my entire mod order:
https://loadorderlibrary.com/lists/ron4a1x

**Comment by tr4wzified** [comment]
Thanks for the report! Would you mind also taking a screenshot of the Sparks spell in xEdit, and sharing it here?

**Comment by ronamit** [comment]
Sure, I guess you mean FormID 0002dd2a
seems like it is only determined by Skyrim.esm

![image](https://user-images.githubusercontent.com/23059549/113469855-93f15900-9459-11eb-8938-769377952d47.png)

![image](https://user-images.githubusercontent.com/23059549/113469860-a8355600-9459-11eb-81ae-b0ea2ff45fba.png)

**Comment by tr4wzified** [comment]
Completely forgot to reply - sorry for the late answer, but I'm not sure what's going on here. It should be checking the half cost perk name to see which level the spell tome is, and it looks like it's called 'Novice Destruction' here which is completely normal 🤔

**Comment by tr4wzified** [comment]
Can you also take a screenshot of the Half Cost Perk by CTRL-clicking on it to verify the name has Novice in it? Or is some other record overriding it?

**Comment by ron-amit** [comment]
Sure, here it is.

![1](https://user-images.githubusercontent.com/38714011/114348899-dad50200-9b6f-11eb-8a36-58612d7d555b.JPG)
![2](https://user-images.githubusercontent.com/38714011/114348904-dc062f00-9b6f-11eb-9f02-d96887bdeef3.JPG)
![3](https://user-images.githubusercontent.com/38714011/114348909-dd375c00-9b6f-11eb-9677-6c2506ec6db6.JPG)

**Comment by ronamit** [comment]
Sure, no problem. Vokrii makes some strange changes.

![1](https://user-images.githubusercontent.com/23059549/114349360-76ff0900-9b70-11eb-97d0-074243ae55d2.JPG)

![2](https://user-images.githubusercontent.com/23059549/114349369-79f9f980-9b70-11eb-8704-8f7e30ea55a2.JPG)

![3](https://user-images.githubusercontent.com/23059549/114349382-7fefda80-9b70-11eb-89e9-5e9b6e4f79ab.JPG)

**Comment by tr4wzified** [comment]
Yup, because it's called 'Destruction Mastery' it thinks the spell tome is labeled as Master level. I'll open up Vokrii and see if I can get the info needed to label the spell from somewhere else. Thanks for your help!

**Comment by tr4wzified** [comment]
Vokrii is now supported! Closing the issue.
