### ISSUE TITLE
Add settings for classic/alternative

### ISSUE THREAD

**Issue by derickso** [tr4wzified/DisplaySpellTomeLevelPatcher#6]
Per the [modpage](https://www.nexusmods.com/skyrimspecialedition/mods/38941):

Classic: Choose this version if you want spell tome level to be displayed as follows -> Spell Tome (Apprentice): Soul Trap
Alternative: Choose this version if you want spell tome level to be displayed as follows -> Apprentice Spell Tome: Soul Trap

        public static string GenerateSpellTomeName(string spellTomeName, string level)
        {
            if (Settings.NamingMode == NamingConvention.Alternative)
            {
                return spellTomeName.ToString().Replace("Spell Tome:", $"{level} Spell Tome:");
            }
            return spellTomeName.ToString().Replace("Spell Tome:", $"Spell Tome ({level}):");
        }

**Comment by tr4wzified** [comment]
Shouldn't be too hard, I'll look at this later this week :)

**Comment by tr4wzified** [comment]
Well, that was a long week, but it's in now :)

**Comment by tr4wzified** [comment]
Changed it again, custom formatting options are available now.
