### ISSUE TITLE
Patch labels spells wrong

### ISSUE THREAD

**Issue by JJMAIHEM** [tr4wzified/DisplaySpellTomeLevelPatcher#8]
For example it labels Novice Spells as Expert ones
![image](https://user-images.githubusercontent.com/5843379/117784572-fea96780-b243-11eb-9afb-c20e673e2c8d.png)
![image](https://user-images.githubusercontent.com/5843379/117785218-a888f400-b244-11eb-84b3-edfd07ef2ff3.png)

Using Cosmonach plugin as Perk Overhaul.

**Comment by tr4wzified** [comment]
Since level is not determined by using the half cost perk anymore this should have been fixed sometime ago
